package mx.unam.ciencias.is.modelo;
// Generated 25-feb-2018 23:47:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int empleadoId;
     private String nombre;
     private String apellido;
     private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

    public Empleado() {
    }

	
    public Empleado(int empleadoId, String nombre, String apellido) {
        this.empleadoId = empleadoId;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Empleado(int empleadoId, String nombre, String apellido, Set<Proyecto> proyectos) {
       this.empleadoId = empleadoId;
       this.nombre = nombre;
       this.apellido = apellido;
       this.proyectos = proyectos;
    }
   
    public int getEmpleadoId() {
        return this.empleadoId;
    }
    
    public void setEmpleadoId(int empleadoId) {
        this.empleadoId = empleadoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set<Proyecto> getProyectos() {
        return this.proyectos;
    }
    
    public void setProyectos(Set<Proyecto> proyectos) {
        this.proyectos = proyectos;
    }




}


