package mx.unam.ciencias.is.modelo;
// Generated 25-feb-2018 23:47:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto  implements java.io.Serializable {


     private int proyectoId;
     private String nombre;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);

    public Proyecto() {
    }

	
    public Proyecto(int proyectoId, String nombre) {
        this.proyectoId = proyectoId;
        this.nombre = nombre;
    }
    public Proyecto(int proyectoId, String nombre, Set<Empleado> empleados) {
       this.proyectoId = proyectoId;
       this.nombre = nombre;
       this.empleados = empleados;
    }
   
    public int getProyectoId() {
        return this.proyectoId;
    }
    
    public void setProyectoId(int proyectoId) {
        this.proyectoId = proyectoId;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


